cc_library(
  name = "process_tree",
  srcs = ["process.cc", "tree.cc"],
  hdrs = ["process.h", "tree.h"],
  deps = [
      "@com_google_absl//absl/container:flat_hash_map",
      "@com_google_absl//absl/synchronization:mutex",
  ]
)
